export const orders = [
  {
    code: 'Paten-GR-260726-0018',
    customer: 'Budi Santoso',
    phone: '0812-4400-7718',
    service: 'GR',
    serviceName: 'Giling + roasting',
    weight: '10,000 kg',
    roast: 'MEDIUM',
    grind: 'MEDIUM',
    total: 'Rp120.000',
    paid: 'Rp50.000',
    remaining: 'Rp70.000',
    paymentStatus: 'DP',
    orderStatus: 'MENUNGGU',
    createdAt: '10:30',
  },
  {
    code: 'Paten-R-260726-0017',
    customer: 'Rina Kopi',
    phone: '0813-1112-9017',
    service: 'R',
    serviceName: 'Roasting saja',
    weight: '8,500 kg',
    roast: 'DARK',
    grind: '-',
    total: 'Rp85.000',
    paid: 'Rp85.000',
    remaining: 'Rp0',
    paymentStatus: 'LUNAS',
    orderStatus: 'DIPROSES',
    createdAt: '10:12',
  },
  {
    code: 'Paten-G-260726-0016',
    customer: 'Pak Hasan',
    phone: '0857-0088-1616',
    service: 'G',
    serviceName: 'Giling saja',
    weight: '25,000 kg',
    roast: '-',
    grind: 'HALUS',
    total: 'Rp125.000',
    paid: 'Rp0',
    remaining: 'Rp125.000',
    paymentStatus: 'BELUM_BAYAR',
    orderStatus: 'SIAP_DIAMBIL',
    createdAt: '09:48',
  },
  {
    code: 'Paten-GR-260726-0015',
    customer: 'Sari Roastery',
    phone: '0821-6620-4415',
    service: 'GR',
    serviceName: 'Giling + roasting',
    weight: '12,000 kg',
    roast: 'LIGHT',
    grind: 'MEDIUM',
    total: 'Rp144.000',
    paid: 'Rp144.000',
    remaining: 'Rp0',
    paymentStatus: 'LUNAS',
    orderStatus: 'SELESAI',
    createdAt: '09:20',
  },
] as const

export const customers = [
  {
    id: 'cust-001',
    name: 'Budi Santoso',
    phone: '0812-4400-7718',
    address: 'Jl. Mawar No. 12, Bukittinggi',
    notes: 'Sering meminta roast medium dan gilingan medium.',
    orders: 12,
    volume: '128 kg',
    receivable: 'Rp70.000',
    lastOrder: 'Hari ini',
  },
  {
    id: 'cust-002',
    name: 'Rina Kopi',
    phone: '0813-1112-9017',
    address: 'Pasar Atas Blok B No. 8',
    notes: 'Preferensi roasting dark untuk batch robusta.',
    orders: 8,
    volume: '74 kg',
    receivable: 'Rp0',
    lastOrder: 'Hari ini',
  },
  {
    id: 'cust-003',
    name: 'Pak Hasan',
    phone: '0857-0088-1616',
    address: 'Nagari Koto Baru',
    notes: 'Biasanya bayar saat pengambilan.',
    orders: 19,
    volume: '305 kg',
    receivable: 'Rp125.000',
    lastOrder: 'Hari ini',
  },
  {
    id: 'cust-004',
    name: 'Sari Roastery',
    phone: '0821-6620-4415',
    address: 'Jl. Sudirman No. 21',
    notes: 'Pelanggan volume besar, perlu label jelas.',
    orders: 27,
    volume: '412 kg',
    receivable: 'Rp0',
    lastOrder: 'Kemarin',
  },
] as const

export const payments = [
  {
    code: 'PAY-0018-A',
    orderCode: 'Paten-GR-260726-0018',
    customer: 'Budi Santoso',
    type: 'DOWN_PAYMENT',
    method: 'CASH',
    amount: 'Rp50.000',
    staff: 'Ilham',
    time: '10:31',
    note: 'DP saat kopi masuk.',
  },
  {
    code: 'PAY-0017-A',
    orderCode: 'Paten-R-260726-0017',
    customer: 'Rina Kopi',
    type: 'FULL_PAYMENT',
    method: 'CASH',
    amount: 'Rp85.000',
    staff: 'Ilham',
    time: '10:14',
    note: 'Lunas di awal.',
  },
  {
    code: 'PAY-0015-B',
    orderCode: 'Paten-GR-260726-0015',
    customer: 'Sari Roastery',
    type: 'REMAINING_PAYMENT',
    method: 'CASH',
    amount: 'Rp94.000',
    staff: 'Ayu',
    time: '09:56',
    note: 'Pelunasan saat serah terima.',
  },
] as const

export const services = [
  {
    code: 'G',
    name: 'Giling saja',
    price: 'Rp5.000',
    status: 'Aktif',
    updatedBy: 'Owner',
    description: 'Layanan penggilingan kopi tanpa proses roasting.',
    todayOrders: '8 order',
    todayWeight: '64 kg',
    todayRevenue: 'Rp320.000',
  },
  {
    code: 'R',
    name: 'Roasting saja',
    price: 'Rp10.000',
    status: 'Aktif',
    updatedBy: 'Owner',
    description: 'Layanan roasting untuk kopi yang sudah siap diproses.',
    todayOrders: '4 order',
    todayWeight: '38 kg',
    todayRevenue: 'Rp380.000',
  },
  {
    code: 'GR',
    name: 'Giling + roasting',
    price: 'Rp12.000',
    status: 'Aktif',
    updatedBy: 'Owner',
    description: 'Paket layanan roasting lalu penggilingan sesuai preferensi pelanggan.',
    todayOrders: '6 order',
    todayWeight: '80,5 kg',
    todayRevenue: 'Rp966.000',
  },
] as const

export const users = [
  {
    name: 'Ilham',
    username: 'owner',
    role: 'OWNER',
    status: 'Aktif',
    lastLogin: 'Hari ini 10:02',
    activity: 'Mengubah harga layanan',
  },
  {
    name: 'Ayu',
    username: 'ayu.staff',
    role: 'STAFF',
    status: 'Aktif',
    lastLogin: 'Hari ini 09:21',
    activity: 'Mencatat pembayaran',
  },
  {
    name: 'Rafi',
    username: 'rafi.staff',
    role: 'STAFF',
    status: 'Aktif',
    lastLogin: 'Kemarin 16:44',
    activity: 'Mengubah status pesanan',
  },
] as const

export const pickups = [
  {
    orderCode: 'Paten-GR-260726-0015',
    recipientName: 'Sari Roastery',
    recipientType: 'CUSTOMER',
    recipientPhone: '0821-6620-4415',
    handedOverBy: 'Ayu',
    pickedUpAt: '26 Juli 2026 09:58',
    photoStatus: 'Tersimpan',
    notes: 'Pesanan diserahkan langsung ke pelanggan.',
  },
  {
    orderCode: 'Paten-G-260726-0016',
    recipientName: 'Fajar',
    recipientType: 'REPRESENTATIVE',
    recipientPhone: '0812-9000-1616',
    handedOverBy: 'Ilham',
    pickedUpAt: 'Belum diserahkan',
    photoStatus: 'Belum ada',
    notes: 'Menunggu pelunasan saat pengambilan.',
  },
] as const

export const reportDetails = {
  cash: {
    title: 'Detail penerimaan tunai',
    metric: 'Rp1.820.000',
    description: 'Drill-down pembayaran berdasarkan tanggal paid_at dan petugas penerima.',
    rows: payments.map((payment) => ({
      label: payment.code,
      primary: payment.amount,
      secondary: payment.customer,
      status: payment.type,
    })),
  },
  orders: {
    title: 'Detail nilai transaksi',
    metric: 'Rp2.166.000',
    description: 'Drill-down nilai order berdasarkan tanggal dibuat, bukan kas masuk.',
    rows: orders.map((order) => ({
      label: order.code,
      primary: order.total,
      secondary: order.customer,
      status: order.orderStatus,
    })),
  },
  receivables: {
    title: 'Detail belum lunas',
    metric: 'Rp740.000',
    description: 'Order aktif dengan remaining_amount lebih besar dari nol.',
    rows: orders
      .filter((order) => order.remaining !== 'Rp0')
      .map((order) => ({
        label: order.code,
        primary: order.remaining,
        secondary: order.customer,
        status: order.paymentStatus,
      })),
  },
  services: {
    title: 'Detail volume layanan',
    metric: '182,5 kg',
    description: 'Kilogram dan nilai transaksi per layanan G, R, dan GR.',
    rows: services.map((service) => ({
      label: service.name,
      primary: service.todayWeight,
      secondary: service.todayRevenue,
      status: service.code,
    })),
  },
} as const

export const auditLogs = [
  {
    id: 'AUD-260726-001',
    actor: 'Ilham',
    action: 'SERVICE_PRICE_UPDATED',
    entity: 'services/GR',
    time: '26 Juli 2026 08:30',
    summary: 'Harga layanan Giling + roasting dikonfirmasi aktif.',
    metadata: {
      before: 'Rp12.000',
      after: 'Rp12.000',
      source: 'Mock admin settings',
    },
  },
  {
    id: 'AUD-260726-002',
    actor: 'Ayu',
    action: 'ORDER_STATUS_CHANGED',
    entity: 'orders/Paten-GR-260726-0015',
    time: '26 Juli 2026 09:56',
    summary: 'Order ditandai selesai setelah pembayaran lunas.',
    metadata: {
      before: 'SIAP_DIAMBIL',
      after: 'SELESAI',
      source: 'Mock pickup flow',
    },
  },
] as const
